config/routes.rb
Rails.application.routes.draw do
  get 'admin_views/userReport'

  get 'admin_views/aManage'

  get 'sample_pages/assessment'

  get 'sample_pages/UCPDResults'

  get 'sample_pages/UCPD'

  get 'sample_pages/ADRDBM'

  get 'sample_pages/UADD'

  get 'admin_views/dashboard'

  get 'admin_views/assign'

  get 'admin_views/scores'

  get 'admin_views/users'

  get 'admin_views/index'

  get 'sample_pages/assign'

  get 'sample_pages/customize'

  get 'sample_pages/scores'

  get 'sample_pages/users'

  root 'admin_views#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/knowledge_domain.rb
class KnowledgeDomain < ApplicationRecord
end

app/controllers/admin_views_controller.rb
class AdminViewsController < ApplicationController
  def dashboard
  end

  def assign
  end

  def scores
  end

  def users
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/knowledge_domains_controller.rb
class KnowledgeDomainsController < ApplicationController
  before_action :set_knowledge_domain, only: [:show, :edit, :update, :destroy]

  # GET /knowledge_domains
  # GET /knowledge_domains.json
  def index
    @knowledge_domains = KnowledgeDomain.all
  end

  # GET /knowledge_domains/1
  # GET /knowledge_domains/1.json
  def show
  end

  # GET /knowledge_domains/new
  def new
    @knowledge_domain = KnowledgeDomain.new
  end

  # GET /knowledge_domains/1/edit
  def edit
  end

  # POST /knowledge_domains
  # POST /knowledge_domains.json
  def create
    @knowledge_domain = KnowledgeDomain.new(knowledge_domain_params)

    respond_to do |format|
      if @knowledge_domain.save
        format.html { redirect_to @knowledge_domain, notice: 'Knowledge domain was successfully created.' }
        format.json { render :show, status: :created, location: @knowledge_domain }
      else
        format.html { render :new }
        format.json { render json: @knowledge_domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /knowledge_domains/1
  # PATCH/PUT /knowledge_domains/1.json
  def update
    respond_to do |format|
      if @knowledge_domain.update(knowledge_domain_params)
        format.html { redirect_to @knowledge_domain, notice: 'Knowledge domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @knowledge_domain }
      else
        format.html { render :edit }
        format.json { render json: @knowledge_domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /knowledge_domains/1
  # DELETE /knowledge_domains/1.json
  def destroy
    @knowledge_domain.destroy
    respond_to do |format|
      format.html { redirect_to knowledge_domains_url, notice: 'Knowledge domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_knowledge_domain
      @knowledge_domain = KnowledgeDomain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def knowledge_domain_params
      params.require(:knowledge_domain).permit(:name, :description, :score_img)
    end
end

app/controllers/sample_pages_controller.rb
class SamplePagesController < ApplicationController
  def assign
  end

  def customize
  end

  def scores
  end

  def users
  end

  def UADD
  end

  def ADRDBM
  end

  def UCPD
  end

  def UCPDResults
  end

  def assessment
  end
end

app/helpers/admin_views_helper.rb
module AdminViewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/knowledge_domains_helper.rb
module KnowledgeDomainsHelper
end

app/helpers/sample_pages_helper.rb
module SamplePagesHelper
end

app/views/admin_views/aManage.html.erb
<h2>Manage Assessments</h2>

<div class="container-fluid">
	<div class="row">

		<div class="col-sm-8">
			<div class="row">
				<div class="col-sm-8 list">
					<strong>Assessment</strong>
				</div>

				<div class="col-sm-4 list">
				</div>
			</div>

			<div class="row">
				<div class="col-sm-8 list">
					CNA
				</div>

				<div class="col-sm-4 list">
					<button type="button" class="btn"><%= link_to image_tag("edit.png", class:"icon"), admin_views_assign_path %></button>
					<button type="button" class="btn"><%= image_tag("trash.png", class:"icon")%></button>
				</div>
			</div>

			<div class="row">
				<div class="col-sm-8 list">
					CNA- Home Healthcare
				</div>

				<div class="col-sm-4 list">
					<button type="button" class="btn"><%= image_tag("edit.png", class:"icon")%></button>
					<button type="button" class="btn"><%= image_tag("trash.png", class:"icon")%></button>
				</div>
			</div>

			<div class="row">
				<div class="col-sm-8 list">
					RN
				</div>

				<div class="col-sm-4 list">
					<button type="button" class="btn"><%= image_tag("edit.png", class:"icon")%></button>
					<button type="button" class="btn"><%= image_tag("trash.png", class:"icon")%></button>
				</div>
			</div>

			<div class="row">
				<div class="col-sm-8 list">
					MD
				</div>

				<div class="col-sm-4 list">
					<button type="button" class="btn"><%= image_tag("edit.png", class:"icon")%></button>
					<button type="button" class="btn"><%= image_tag("trash.png", class:"icon")%></button>
				</div>
			</div>
		</div>

	</div>
</div>

app/views/admin_views/assign.html.erb
<h1>Assign Content</h1>

<!--<div class="box">
	<div class="dropdown">
	  <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	    Select an Assessment Type
	  </button>
	  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
	    <a class="dropdown-item" id="CNA">CNA</a>
	    <div class="dropdown-divider"></div>
	    <a class="dropdown-item" href="#">RN</a>
	    <div class="dropdown-divider"></div>
	    <a class="dropdown-item" href="#">MD</a>
	  </div>
	</div>
</div>-->

<div class="CNA box">
	<div class="container">
		<div class="row">
			<div class="col-sm-5 col-sm-offset-1 list">
				<div>
					<h3 data-toggle="tooltip" title="Certain KD's will be static. These are the KD's from validated pre-hire assessments that are vital to the role.">Assessment</h3>
				</div>
				<div class="item">
					<p>Activities of Daily Living</p>
				</div>
				<div class="item">
					<p>Basic Nursing Skills</p>
				</div>
				<div class="item">
					<p>Client Rights</p>
				</div>
				<div class="item">
					<p>Psychosocial Care Skills</p>
				</div>
				<div class="item KD1A">
					<p>Behavior Management
						<button id="KD1A" style="float:right" type="button" class="btn btn-default">
	          -
	        	</button> 
	      	</p>
				</div>
				<div class="item KD2A">
					<p>Identify Stage of Dementia
						<button id="KD2A" style="float:right" type="button" class="btn btn-default">
	          -
	        	</button> 
					</p>
				</div>
				<div class="item KD3A">
					<p>Use Verbal Communication
						<button id="KD3A" style="float:right" type="button" class="btn btn-default">
	          -
	        	</button> 
					</p>
				</div>
				<div class="item KD4A">
					<p>Use Non-verbal Communication
						<button id="KD4A"  style="float:right" type="button" class="btn btn-default">
	          -
	        	</button> 
					</p>
				</div>
			</div>
			<div class="col-sm-5 col-sm-offset-1 list">
				<div>
					<h3 data-toggle="tooltip" title="Suggestions are based on frequently used KD's from the specific system or hospital, and from frequently assigned KD's for the specific role from a nationwide pool.">Suggested Additions</h3>
				</div>
				<div class="item KD1B">
					<p>Behavior Management
						<button id="KD1B" style="float:right" type="button" class="btn btn-default btn-sm btn-glyphicon">
	          +
	        </button> 
					</p>
				</div>
				<div class="item KD2B">
					<p>Identify Stage of Dementia
						<button id="KD2B" style="float:right" type="button" class="btn btn-default btn-sm">
	          +
	        </button> 
					</p>
				</div>
				<div class="item KD3B">
					<p>Use Verbal Communication
						<button id="KD3B" style="float:right" type="button" class="btn btn-default btn-sm">
	          +
	        </button> 
					</p>
				</div>
				<div class="item KD4B">
					<p>Use Non-Verbal Communication
						<button id="KD4B" style="float:right" type="button" class="btn btn-default btn-sm btn-glyphicon">
	          +
	        	</button> 
					</p>
				</div>
			</div>
		</div><!--end row-->
	</div><!--end container-->

	<div class="container-fluid">
		<div class="row justify-content-around">
			<div class="col-sm-1 col-sm-offset-8">
				<button type="button" class="btn btn-warning"><%= link_to("Assign", admin_views_users_path) %></button>
			</div>
			<div class="col-sm-1" data-toggle="tooltip" title="Admins can save customized assessments.">
				<button type="button" class="btn btn-warning"><%= link_to("Save", admin_views_dashboard_path) %></button>
			</div>
		</div><!--end row-->
	</div><!--end container-->
</div>

app/views/admin_views/dashboard.html.erb
<h1>Dashboard</h1>
<div class="container">
	<div class="row">
		<div col-sm-12>
			<h2>Assessment Management</h2>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-4">
			<button type="button" class="btn btn-warning"><%= link_to("Assign Assessments", admin_views_users_path) %></button>
		</div>
		<div class="col-sm-4 col-sm-offset-2">
			<button type="button" class="btn btn-warning"><%= link_to("Manage Assessments", admin_views_aManage_path) %></button>
		</div>
	</div>
</div>


<div class="container">
	<div class="row">
		<div col-sm-12>
			<h2>User Management</h2>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-4">
			<button type="button" class="btn btn-warning"><%= link_to("Reports", admin_views_scores_path) %></button>
		</div>
		<div class="col-sm-4 col-sm-offset-2">
			<button type="button" class="btn btn-warning"><%= link_to("User Profiles", admin_views_users_path) %></button>
		</div>
	</div>
</div>

app/views/admin_views/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6">
			<h2>Admin Views</h2>
			<button type="button" class="btn btn-warning"><%= link_to("Dashboard", admin_views_dashboard_path) %></button>
		</div>

		<div class="col-sm-6">
			<h2>Learner Views</h2>
			<button type="button" class="btn btn-warning">
				<%= link_to("Dashboard", sample_pages_assign_path) %></button>
		</div>
	</div>
</div>

app/views/admin_views/scores.html.erb
<h2>Reports</h2>

<div class="container">
	<div class="row list" style="margin-bottom:3em">
			<div class="col-sm-6 col-sm-offset-3">
				<%= image_tag("reports.png", class: "img-responsive")%>
			</div>
	</div>

	<div class="row list" style="margin-bottom:3em">
		<div class="col-sm-6">
			<%= image_tag("facilityscatterplot.png", class: "img-responsive")%>
		</div>
		<div class="col-sm-6">
			<%= image_tag("userscatterplot.png", class: "img-responsive")%>
		</div>
	</div>

	<div class="row list">
		<div class="col-sm-6 col-sm-offset-3">
			<p>*Images were taken from Gnosis platform. Ideally there would be a robust reporting system where admins could generate custom reports based on job roles, KD's, knowledge gaps, etc.
			</p>
		</div>
	</div>

	<div class="row list">
		<div class="col-sm-6 col-sm-offset-3">
			<p>The admin assigns from the Practice Area, and the learner assessment generates the KD's. Once the learner has taken the assessment, the admin can drill down to the KD level to see what parts of the PA they were assigned, and their progress towards mastery of the KD and subsequent PA</p>
			<button class="btn btn-warning" type="button"><%= link_to("Example of Individual report", admin_views_userReport_path)%></button>
		</div>
	</div>

</div>

app/views/admin_views/userReport.html.erb
<h2>John Doe Report</h2>

<div class="container-fluid">
	<div class="row ldashtop">
		<div class="col-sm-12">
			<h3>Overall Role Competency</h3>
		</div>
		<div class="col-sm-1 red" data-toggle="tooltip" title="Behavior Management">
		</div>
		<div class="col-sm-1 red" data-toggle="tooltip" title="Client Rights">
		</div>
		<div class="col-sm-1 red" data-toggle="tooltip" title="Identify Stage of Dementia">
		</div>
		<div class="col-sm-1 yellow" data-toggle="tooltip" title="Activities of Daily Living">
		</div>
		<div class="col-sm-1 yellow" data-toggle="tooltip" title="Psychosocial Care Skills">
		</div>
		<div class="col-sm-1 yellow" data-toggle="tooltip" title="Use Verbal Communication">
		</div>
		<div class="col-sm-1 green" data-toggle="tooltip" title="Basic Nursing Skills">
		</div>
		<div class="col-sm-1 green" data-toggle="tooltip" title="Use Non-verbal Communication">
		</div>
	</div>

	<div class="row ldashtop">
		<div class="col-sm-10 col-sm-offset-1">
			<div id="accordion">
				<div class="card">
					<div class="card-header" id="headingOne">
						<h5 class="mb-0">
							<button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
								Behavior Management
							</button>
						</h5>
					</div>

					<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
						<div class="card-body">
							The PA would drop down to show the exact KD's assigned to the individual learner and their progress. They would be arranged so the "in progress" courses are displayed first.
						</div>
					</div>
				</div>
				<div class="card">
					<div class="card-header" id="headingTwo">
						<h5 class="mb-0">
							<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
								Client Rights
							</button>
						</h5>
					</div>
					<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
						<div class="card-body">
							The PA would drop down to show the exact KD's assigned to the individual learner and their progress.
						</div>
					</div>
				</div>
				<div class="card">
					<div class="card-header" id="headingThree">
						<h5 class="mb-0">
							<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
								Identify Stage of Dementia
							</button>
						</h5>
					</div>
					<div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
						<div class="card-body">
							The PA would drop down to show the exact KD's assigned to the individual learner and their progress.
						</div>
					</div>
				</div>
			</div>
		</div>
</div>

app/views/admin_views/users.html.erb
<h1>Users</h1>

<div class="container">
	<div class="row">
		<div class="col-sm-6">
			<input type="text" id="myInput" placeholder="Filter by date of hire, name, or job role" data-toggle="tooltip" title="Instead of a search function, this would be a filter function.">
		</div>

		<div class="col-sm-2 col-sm-offset-2">
			<p>Select All
				<input class="checkbox" type="checkbox" name="select-all" id="select-all"/>
			</p>
			
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-sm-8 list">
			<div class="row item">
				<div class="col-sm-4">
					<p>Block, A.</p>
				</div>
				<div class="col-sm-4">
					<p>RN</p>
				</div>
				<div class="col-sm-4">
					<input class="checkbox" type="checkbox" name="checkbox-1" id="checkbox-1"/>
				</div>
			</div>

			<div class="row item">
				<div class="col-sm-4">
					<p><%= link_to("Doe, J.", admin_views_userReport_path)%></p>
				</div>
				<div class="col-sm-4">
					<p>CNA</p>
				</div>
				<div class="col-sm-4">
					<input class="checkbox" type="checkbox" name="checkbox-1" id="checkbox-1"/>
				</div>
			</div>

			<div class="row item">
				<div class="col-sm-4">
					<p>Person, D.</p>
				</div>
				<div class="col-sm-4">
					<p>RN</p>
				</div>
				<div class="col-sm-4">
					<input class="checkbox" type="checkbox" name="checkbox-1" id="checkbox-1"/>
				</div>
			</div>

			<div class="row item">
				<div class="col-sm-4">
					<p>Tannenbaum, O.</p>
				</div>
				<div class="col-sm-4">
					<p>CNA</p>
				</div>
				<div class="col-sm-4">
					<input class="checkbox" type="checkbox" name="checkbox-1" id="checkbox-1"/>
				</div>
			</div>

			<div class="row item">
				<div class="col-sm-4">
					<p>Vent, N.</p>
				</div>
				<div class="col-sm-4">
					<p>MD</p>
				</div>
				<div class="col-sm-4">
					<input class="checkbox" type="checkbox" name="checkbox-1" id="checkbox-1"/>
				</div>
			</div>
		</div>

		<div class="col-sm-3 col-sm-offset2">
			<div class="dropdown">
				<button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Assessment List
				</button>
				<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
					<a class="dropdown-item" id="CNA-assign">CNA</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="#">RN</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="#">MD</a>
				</div>
			</div>
			<button type="button" class="btn btn-warning" id="assign"><%= link_to("Assign", admin_views_dashboard_path) %></button>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mockup AL</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="header_wrapper" class="header-static-top" rolse="banner">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">
          <%= image_tag("logo.png", class: "img-responsive logo") %>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Admin Views
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <ul>
                  <li><%= link_to("Dashboard", admin_views_dashboard_path) %></li>
                  <li><%= link_to("Assessments", admin_views_assign_path) %></li>
                  <li><%= link_to("Users", admin_views_users_path) %></li>
                  <li><%= link_to("Reports", admin_views_scores_path) %></li>
                </ul>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Learner Views
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <ul>
                  <li><%= link_to("Dashboard", sample_pages_assign_path) %></li>
                  <li><%= link_to("Profile", sample_pages_users_path) %></li>
                  <li><%= link_to("Reports", sample_pages_scores_path) %></li>
                </ul>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    </div>

    <%= yield %>
    <footer>

    </footer>

  </body>
</html>

app/views/sample_pages/UCPD.html.erb
<h2>Course</h2>

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
			<%= image_tag("ucpd.jpg", class: "img-responsive")%>
		</div>
		<div class="col-sm-12 box">
			<p>Feedback will be given at every knowledge check to reinforce their understanding. All answers will influence the content provided during the course and be accounted for in their overall competency score.</p>
		</div>
		<div class="col-sm-3 col-sm-offset-2">
			<button type="button" class="btn btn-warning"><%= link_to("Take the Assessment", sample_pages_assessment_path)%></button>
	</div>
</div>

app/views/sample_pages/UCPDResults.html.erb
<h1>SamplePages#UCPDResults</h1>
<p>Find me in app/views/sample_pages/UCPDResults.html.erb</p>

app/views/sample_pages/assessment.html.erb
<h2>Assessment</h2>

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12" id="course">
			<%= image_tag("assessmentucpd.png", class: "img-responsive")%>
		</div>
	</div>

		<div class="col-sm-12 ldashtop" id="courseReport">
			Course Report
			<div class="row">
				<div class="col-sm-3 list">
					<strong>Knowledge Domain</strong>
				</div>
				<div class="col-sm-3 col-sm-offset-2 list" data-toggle="tooltip" title="This sections should compare the original KD score (original assessment) to the new score (post-course assessment). Should this score be a numerical value?">
					<strong>Score</strong>
				</div>
			</div>

			<div class="row">
				<div class="col-sm-3 list">
					Behavior Managment
				</div>
				<div class="col-sm-3 col-sm-offset-2 list">
				</div>
			</div>


			<div class="row">
				<div class="col-sm-3 list">
					Identify Stage of Dementia
				</div>
				<div class="col-sm-3 col-sm-offset-2 list">
				</div>
			</div>


			<div class="row">
				<div class="col-sm-3 list">
					Use Verbal Communication
				</div>
				<div class="col-sm-3 col-sm-offset-2 list">
				</div>
			</div>


			<div class="row">
				<div class="col-sm-3 list">
					Use Non-Verbal Communication
				</div>
				<div class="col-sm-3 col-sm-offset-2 list">
				</div>
			</div>

		</div>

		</div>
	</div>

	<div class="row">
		<div class="col-sm-2 col-sm-offset-8">
			<button type="button" class="btn btn-warning" id="assessmentSubmit">Submit</button>
			<button type="button" class="btn btn-warning" id="dashbutton"><%= link_to("Dashboard", sample_pages_assign_path)%></button>
		</div>
	</div>
</div>

app/views/sample_pages/assign.html.erb
<h2>Dashboard</h2>

<div class="container-fluid">
	<div class="row ldashtop">
		<div class="col-sm-4">
			<button type="button" class="btn btn-warning" id="dashview1">View- Take Assessment</button>
		</div>
		<div class="col-sm-4 col-sm-offset-2">
			<button type="button" class="btn btn-warning" id="dashview2">View- Assessment Taken</button>
		</div>
	</div>
</div>

<div class="container-fluid" id="assessmentNotTaken">
	<div class="row ldashtop">
		<div class="col-sm-5">
			<p>CNA Assessment</p>
		</div>
		
		<div class="col-sm-5 col-sm-offset-2">
			<button type="button" class="btn btn-warning"><%= link_to("Take Assessment", sample_pages_assessment_path) %></button>
		</div>
	</div>
</div>

<div class="container-fluid" id="assessmentTaken">
	<div class="row ldashtop">
		<div class="col-sm-12">
			<h3>Overall Role Competency</h3>
		</div>
		<div class="col-sm-1 red" data-toggle="tooltip" title="Behavior Management">
		</div>
		<div class="col-sm-1 red" data-toggle="tooltip" title="Client Rights">
		</div>
		<div class="col-sm-1 red" data-toggle="tooltip" title="Identify Stage of Dementia">
		</div>
		<div class="col-sm-1 yellow" data-toggle="tooltip" title="Activities of Daily Living">
		</div>
		<div class="col-sm-1 yellow" data-toggle="tooltip" title="Psychosocial Care Skills">
		</div>
		<div class="col-sm-1 yellow" data-toggle="tooltip" title="Use Verbal Communication">
		</div>
		<div class="col-sm-1 green" data-toggle="tooltip" title="Basic Nursing Skills">
		</div>
		<div class="col-sm-1 green" data-toggle="tooltip" title="Use Non-verbal Communication">
		</div>
	</div>

	<div class="row">
		<div class="col-sm-12">
			<h3 data-toggle="tooltip" title="When all courses get modularized, this can reflect the KD's instead of referring to course titles.">Courses In Progress</h3>
		</div>
		<div class="col-sm-3 col-sm-offset-1 learnerKD">
			<p>
				<%= link_to "Understanding Communication in Persons with Dementia", sample_pages_UCPD_path, :class=> "h4"%>
				<ul>
					<li>Behavior Management</li>
					<li>Identify Stage of Dementia</li>
					<li>Use Verbal Communication</li>
					<li>Understanding Alzheimer's Disease and Dementia</li>
				</ul>
			</p>
		</div>
		<div class="col-sm-3 col-sm-offset-1 learnerKD">
			<p>
				<%= link_to "Alzheimer's Disease and Related Disorders: Behavior Management", sample_pages_ADRDBM_path, :class=> "h4"%>
				<ul>
					<li>Behavior Management</li>
					<li>Identify Stage of Dementia</li>
					<li>Use Verbal Communication</li>
					<li>Understanding Alzheimer's Disease and Dementia</li>
				</ul>
			</p>
		</div>
		<div class="col-sm-3 col-sm-offset-1 learnerKD">
			<p>
				<h4>Understanding Client's Rights</h4>
				<ul>
					<li>Client Rights</li>
				</ul>
			</p>
		</div>
		<div class="col-sm-3 col-sm-offset-1 learnerKD">
			<p>
				<h4>In-Home Healthcare</h4>
				<ul>
					<li>Activities of Daily Living</li>
					<li>Client Rights</li>
				</ul>
			</p>
		</div>
</div>